# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('code', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainline_revenue', models.DecimalField(decimal_places=2, max_digits=7)),
                ('regional_revenue', models.DecimalField(decimal_places=2, max_digits=7)),
                ('other_revenue', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=7)),
                ('salaries_wages', models.DecimalField(decimal_places=2, max_digits=7)),
                ('aircraft_fuel', models.DecimalField(decimal_places=2, max_digits=7)),
                ('depreciation_amortization', models.DecimalField(decimal_places=2, max_digits=7)),
                ('interest_expense', models.DecimalField(decimal_places=2, max_digits=7)),
                ('other_expenses', models.DecimalField(decimal_places=2, max_digits=7)),
                ('operating_expenses', models.DecimalField(decimal_places=2, max_digits=7)),
                ('operating_result', models.DecimalField(decimal_places=2, max_digits=7)),
                ('non_operating_items', models.DecimalField(decimal_places=2, max_digits=7)),
                ('net_result', models.DecimalField(decimal_places=2, max_digits=7)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Airline')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, choices=[(2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016)], null=True)),
            ],
        ),
        migrations.AddField(
            model_name='financialdata',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Year'),
        ),
    ]
