# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('flight_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('departures', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rev_pax_miles', models.DecimalField(decimal_places=2, max_digits=6)),
                ('avail_seat_miles', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fuel_gallons', models.DecimalField(decimal_places=2, max_digits=6)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Airline')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Year')),
            ],
        ),
    ]
