# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_statsdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsdata',
            name='avail_seat_miles',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
        migrations.AlterField(
            model_name='statsdata',
            name='rev_pax_miles',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
